### ISSUE TITLE
Nginx not compiled with --with-threads argument to the configure command

### ISSUE THREAD

**Issue by kriptor** [bitnami/bitnami-docker-nginx#148] opened 2020-11-01 22:34 UTC
Hi,

is there a particular reason for nginx not being compiled with thread pool support?
Would it be possible to include this nginx feature in the near future?

Thx

**Comment by juan131** [comment] 2020-11-03 07:46
Closing as duplicate of https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues/36

**Closed by juan131** 2020-11-03 07:46 UTC
